databases:
  - name: contactdb
    plan: free
    databaseName: contacts_db
    user: contacthub_user

services:
  - type: web
    plan: free
    name: Contacthub
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn Contacthub.asgi:application -k uvicorn.workers.UvicornWorker' 
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contactdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
